FROM python:3.9-alpine

WORKDIR /home/ftq

COPY data data

COPY service service

COPY utils utils

COPY ["game.py", "round.py", "__init__.py", "./"]

COPY server.py server.py

CMD ["python", "server.py"]



